### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by evlsmurf** [nixton9/HomePage#2]
How would someone run this? Possible to run on raspberry pi? Looks like alot more then the normal start page im use too.

**Comment by nixton9** [comment]
This runs on the browser, so I would say yes. You can deploy this on a service like Heroku, for example.

**Comment by iampavangandhi** [comment]
@nixton9 Great Homepage :+1: Its better if you deploy it so everyone can see and use it

**Comment by DerEyve** [comment]
How do I install it?

**Comment by nixton9** [comment]
> @nixton9 Great Homepage 👍 Its better if you deploy it so everyone can see and use it

Thank you! I haven't done that because this startpage uses some API's that have a limited usage. They would easily be maxed out and most of the stuff would stop working.

**Comment by nixton9** [comment]
> How do I install it?

You'll need to follow the steps on the readme file and then deploy it online using a service like Heroku for example

**Comment by evlsmurf** [comment]
The issue is the deploying part, most of the start pages are simple to deploy via github pages or hosting local on PC. This is harder to deploy for people that have no knowledge of heroku. The steps for setting up the .env are easy as thats just a text file you create.

**Comment by DerEyve** [comment]
> The issue is the deploying part, most of the start pages are simple to deploy via github pages or hosting local on PC. This is harder to deploy for people that have no knowledge of heroku. The steps for setting up the .env are easy as thats just a text file you create.

Thats actually what i meant with "How do I install it?". I have zero experience with heroku.

**Comment by tphjsz** [comment]
> Thats actually what i meant with "How do I install it?". I have zero experience with heroku. So a nicer Installation manual would be better and easier to understand for everyone

I didn't have experience with git, heroku or api and managed to get working. 

If you have experience with Github, then the heroku is the easiest part to be honest (I got pretty lost trying to set up the repo on github). 
Just create your account, click on "New" on the right side of the dashboard and "Create new app".  From there, connect your github account, search for your repository and select the one with the homepage and click on "Deploy branch". 
After the building process you can click on "Open app" and it will open a link like this: https://_YOUR-APP-NAME_.herokuapp.com. That's your homepage.

**Comment by evlsmurf** [comment]
> 
> 
> > Thats actually what i meant with "How do I install it?". I have zero experience with heroku. So a nicer Installation manual would be better and easier to understand for everyone
> 
> I didn't have experience with git, heroku or api and managed to get working.
> 
> If you have experience with Github, then the heroku is the easiest part to be honest (I got pretty lost trying to set up the repo on github).
> Just create your account, click on "New" on the right side of the dashboard and "Create new app". From there, connect your github account, search for your repository and select the one with the homepage and click on "Deploy branch".
> After the building process you can click on "Open app" and it will open a link like this: https://_YOUR-APP-NAME_.herokuapp.com. That's your homepage.

Where are you inputting the .env info in a file on git or using heroku Config Vars section?

**Comment by tphjsz** [comment]
> Where are you inputting the .env info in a file on git or using heroku Config Vars section?

On git. 
Just a file named ".env" inside the **_client_** folder.

**Comment by evlsmurf** [comment]
> 
> 
> > Where are you inputting the .env info in a file on git or using heroku Config Vars section?
> 
> On git.
> Just a file named ".env" inside the **_client_** folder.

and that fork is private correct on your end so no one can get that info? Also how do i go about getting the google api's that's very confusing for me

**Comment by nixton9** [comment]
@evlsmurf @tphjsz  to avoid having the .env file on your Github you can just use Config vars on Heroku - I personally do that.

**Comment by nixton9** [comment]
Guys, sorry this is not super straight forward to get up and running but I wanted to get this repo public since some people were asking for it. I'll try to make things easier when I have some time.

In the meanwhile, you can check how to deploy on Heroku with this - https://www.eduardo-araujo.com/tips/post-202. It's really quite simple!

**Comment by tphjsz** [comment]
> and that fork is private correct on your end so no one can get that info? Also how do i go about getting the google api's that's very confusing for me

Yes, the repo I created is private, but I might just do as @nixton9 suggested. 
To get google api I had to create a project on cloud.google.com.  I got the api key from there. You can watch a youtube video on how to get the gmail api key.

**Comment by evlsmurf** [comment]
> 
> 
> Guys, sorry this is not super straight forward to get up and running but I wanted to get this repo public since some people were asking for it. I'll try to make things easier when I have some time.
> 
> In the meanwhile, you can check how to deploy on Heroku with this - https://www.eduardo-araujo.com/tips/post-202. It's really quite simple!

Got it running just having issues with gmail part and movies/tv

**Comment by nixton9** [comment]
> > Guys, sorry this is not super straight forward to get up and running but I wanted to get this repo public since some people were asking for it. I'll try to make things easier when I have some time.
> > In the meanwhile, you can check how to deploy on Heroku with this - https://www.eduardo-araujo.com/tips/post-202. It's really quite simple!
> 
> Got it running just having issues with gmail part and movies/tv

Any errors on the console?
Are you trying it locally or is this deployed?

**Comment by evlsmurf** [comment]
> Any errors on the console?
> Are you trying it locally or is this deployed?

Its deployed on Heroku i can access dash but Movies/TV feed and Gmail aren't working.
The gmail part i think im just not doing the api stuff on google's end correct and ive tried different ways 
the movies and tv no idea just says "There was an error fetching movies"

**Comment by nixton9** [comment]
> > Any errors on the console?
> > Are you trying it locally or is this deployed?
> 
> Its deployed on Heroku i can access dash but Movies/TV feed and Gmail aren't working.
> The gmail part i think im just not doing the api stuff on google's end correct and ive tried different ways
> the movies and tv no idea just says "There was an error fetching movies"

Try this:
Open and run the project locally with 'npm run dev' after having created the .env file ofc. Then, go to the file MoviesContainer.tsx and add 'console.log(err)' on line 63 and on line 89. Then run the app and tell me what errors you see on the console when you go the movies page

**Comment by evlsmurf** [comment]
no idea how to get running local

**Comment by nixton9** [comment]
> no idea how to get running local

Just run the command 'npm run dev' on the project's directory

**Comment by evlsmurf** [comment]
cant figure out running local i have zero knowledge of using npm

**Comment by nixton9** [comment]
> cant figure out running local i have zero knowledge of using npm

Just make sure you have node installed on your machine first. After this is done, using the command line, go to the project's folder and just write: npm run dev. This will run the project locally. If you want to learn a bit about npm check something like this: https://nodesource.com/blog/an-absolute-beginners-guide-to-using-npm/

**Comment by evlsmurf** [comment]
Getting this error trying to run it 

`C:\Users\Chris\Downloads\HomePage-master>npm run dev

> homepage@1.0.0 dev C:\Users\Chris\Downloads\HomePage-master
> concurrently --kill-others "npm run start" "npm run client"

'concurrently' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homepage@1.0.0 dev: `concurrently --kill-others "npm run start" "npm run client"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the homepage@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chris\AppData\Roaming\npm-cache\_logs\2020-08-31T13_41_18_976Z-debug.log`

**Comment by nixton9** [comment]
Before doing that, just do 'npm install'

**Comment by evlsmurf** [comment]
> 
> 
> Before doing that, just do 'npm install'

C:\Users\Chris\Downloads\HomePage-master>npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN mini-create-react-context@0.4.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-icons@3.10.0 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
npm WARN react-resize-detector@2.3.0 requires a peer of react@^0.14.7 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-router@5.2.0 requires a peer of react@>=15 but none is installed. You must install peer dependencies yourself.
npm WARN react-router-dom@5.2.0 requires a peer of react@>=15 but none is installed. You must install peer dependencies yourself.
npm WARN react-smooth@1.0.5 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-smooth@1.0.5 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@2.9.0 requires a peer of react@>=15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-transition-group@2.9.0 requires a peer of react-dom@>=15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN recharts@1.8.5 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN recharts@1.8.5 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN homepage@1.0.0 No repository field.

audited 335 packages in 1.259s

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by evlsmurf** [comment]
When running npm run dev

```
C:\Users\Chris\Downloads\HomePage-master>npm run dev

> homepage@1.0.0 dev C:\Users\Chris\Downloads\HomePage-master
> concurrently --kill-others "npm run start" "npm run client"

[1]
[1] > homepage@1.0.0 client C:\Users\Chris\Downloads\HomePage-master
[1] > cd client && npm start
[1]
[0]
[0] ┌────────────────────────────────────────────────────────────────────┐
[0] │                      npm update check failed                       │
[0] │                Try running with sudo or get access                 │
[0] │                to the local update config store via                │
[0] │ sudo chown -R $USER:$(id -gn $USER) C:\Users\Chris\.config │
[0] └────────────────────────────────────────────────────────────────────┘
[0]
[0] > homepage@1.0.0 start C:\Users\Chris\Downloads\HomePage-master
[0] > npm install && node server.js
[0]
[1]
[1] > homepage@0.1.0 start C:\Users\Chris\Downloads\HomePage-master\client
[1] > react-scripts start
[1]
[1] 'react-scripts' is not recognized as an internal or external command,
[1] operable program or batch file.
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! homepage@0.1.0 start: `react-scripts start`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the homepage@0.1.0 start script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\Chris\AppData\Roaming\npm-cache\_logs\2020-08-31T13_51_01_085Z-debug.log
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! homepage@1.0.0 client: `cd client && npm start`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the homepage@1.0.0 client script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\Chris\AppData\Roaming\npm-cache\_logs\2020-08-31T13_51_01_099Z-debug.log
[1] npm run client exited with code 1
--> Sending SIGTERM to other processes..
[0] npm run start exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homepage@1.0.0 dev: `concurrently --kill-others "npm run start" "npm run client"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the homepage@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chris\AppData\Roaming\npm-cache\_logs\2020-08-31T13_51_01_215Z-debug.log
```

**Comment by nixton9** [comment]
Check this and try the solutions shown here - https://stackoverflow.com/questions/47928735/react-scripts-is-not-recognized-as-an-internal-or-external-command

**Comment by evlsmurf** [comment]
> 
> 
> Check this and try the solutions shown here - https://stackoverflow.com/questions/47928735/react-scripts-is-not-recognized-as-an-internal-or-external-command

Its a no go thanks for help but this just isn't worth all this trouble trying local

**Comment by edo0** [comment]
#3 I have been making some progress troubleshooting missing `npm` dependencies. Far from done, but ahead we go

**Comment by nixton9** [comment]
> > Check this and try the solutions shown here - https://stackoverflow.com/questions/47928735/react-scripts-is-not-recognized-as-an-internal-or-external-command
> 
> Its a no go thanks for help but this just isn't worth all this trouble trying local

Just saw what was wrong. Follow the new 'How to guide' on the readme file from the start, and everything should be fine now! Let me know if you have any problems :)

**Comment by evlsmurf** [comment]
Great I’ll try when I get home later! Thanks

**Comment by evlsmurf** [comment]
> 
> 
> > > Any errors on the console?
> > > Are you trying it locally or is this deployed?
> > 
> > 
> > Its deployed on Heroku i can access dash but Movies/TV feed and Gmail aren't working.
> > The gmail part i think im just not doing the api stuff on google's end correct and ive tried different ways
> > the movies and tv no idea just says "There was an error fetching movies"
> 
> Try this:
> Open and run the project locally with 'npm run dev' after having created the .env file ofc. Then, go to the file MoviesContainer.tsx and add 'console.log(err)' on line 63 and on line 89. Then run the app and tell me what errors you see on the console when you go the movies page

Can you show exactly how the line should show with 'console.log(err)' added getting errors when adding and running homepage again but its running with readme setup now just still have issues with gmail and movies

**Comment by tphjsz** [comment]
Are your Google API key setup like this?

![screenshot-console cloud google com-2020 09 02-12_21_36](https://user-images.githubusercontent.com/25311448/92004235-59cfa580-ed18-11ea-8ada-956d9230a84f.jpg)
